@echo off
set OPENAI_API_KEY=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
python meeting_analyzer.py "Senior Project Demo.mp3" --email-config email_config.json
pause 